version: '3.0'
services:
  backend:
    container_name: backend
    build: ./back-spring
    ports:
      - "8080:8080"
    environment: 
      - PORT=8080
  frontend:
    container_name: frontend
    build: ./front-vue
    ports:
      - "3000:3000"
    environment: 
      - PORT=3000
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"