version: '3'
services:
  backend:
    container_name: backend
    build: ./back-spring
    ports:
      - "8082:8081"
  frontend:
    container_name: frontend
    build: ./front-vue
    ports:
      - "3000:3000"
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: nginx:latest
    build: ./.nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "81:80"