import Vue from "vue";

import "./styles/quasar.sass";
import "@quasar/extras/material-icons/material-icons.css";
import "@quasar/extras/fontawesome-v5/fontawesome-v5.css";
import {
  Quasar,
  QLayout,
  QHeader,
  QDrawer,
  QPageContainer,
  QPage,
  QToolbar,
  QToolbarTitle,
  QBtn,
  QIcon,
  QList,
  QItem,
  QItemSection,
  QItemLabel,
  QFooter,
  QCard,
  QCardSection,
  QSeparator,
  QRouteTab,
  QTabs,
  QSpace,
  QExpansionItem,
  QCarousel,
  QCarouselControl,
  QCarouselSlide,
  QImg,
  QScrollArea,
  QField,
  QInput,
  QForm,
  QTab,
  QTabPanels,
  QTabPanel,
  QBtnDropdown,
  QMenu,
  ClosePopup,
  QRadio,
  QCheckbox,
  QChatMessage,
  QBtnToggle,
  QUploader,
  QUploaderAddTrigger,
  QTooltip,
  QTimeline,
  QTimelineEntry,
  QEditor,
  QPopupEdit,
  QSelect,
  QDate,
  QPopupProxy,
  QCardActions,
  QDialog
} from "quasar";

Vue.use(Quasar, {
  config: {},
  components: {
    QLayout,
    QHeader,
    QDrawer,
    QPageContainer,
    QPage,
    QToolbar,
    QToolbarTitle,
    QBtn,
    QIcon,
    QList,
    QItem,
    QItemSection,
    QItemLabel,
    QFooter,
    QCard,
    QCardSection,
    QSeparator,
    QRouteTab,
    QTabs,
    QSpace,
    QExpansionItem,
    QCarousel,
    QCarouselControl,
    QCarouselSlide,
    QImg,
    QScrollArea,
    QField,
    QInput,
    QForm,
    QChatMessage,
    QTab,
    QTabPanels,
    QTabPanel,
    QBtnDropdown,
    QMenu,
    QRadio,
    QCheckbox,
    QBtnToggle,
    QUploader,
    QUploaderAddTrigger,
    QTooltip,
    QTimeline,
    QTimelineEntry,
    QEditor,
    QPopupEdit,
    QSelect,
    QDate,
    QPopupProxy,
    QCardActions,
    QDialog
  },
  directives: {
    ClosePopup
  },
  plugins: {},
  utils: {}
});
